openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /magic:
    post:
      tags:
        - magic-8-ball-controller
      operationId: getRandomResponse
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Magic8Ball'
  /word:
    get:
      tags:
        - word-controller
      operationId: getSingleRandomWord
      responses:
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Word'
  /quote:
    get:
      tags:
        - quote-controller
      operationId: getSingleQuote
      responses:
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    Magic8Ball:
      required:
        - question
      type: object
      properties:
        question:
          type: string
        answer:
          type: string
        id:
          type: integer
          format: int32
    Word:
      type: object
      properties:
        id:
          type: integer
          format: int32
        word:
          type: string
        definition:
          type: string
    Quote:
      type: object
      properties:
        id:
          type: integer
          format: int32
        author:
          type: string
        quote:
          type: string
